artifactVersion: 0.1.0
userAgent: client
invokerPackage: video.api.client.api
apiPackage: video.api.client.api.clients
modelPackage: video.api.client.api.models
groupId: video.api
gitRepoId: api.video-android-client
artifactDescription: api.video Android API client
artifactUrl: https://github.com/apivideo/api.video-android-client
scmConnection: scm:git:git://github.com/apivideo/api.video-android-client.git
scmDeveloperConnection: scm:git:ssh://github.com:apivideo/api.video-android-client.git
scmUrl: https://github.com/apivideo/api.video-android-client
developerName: api.video ecosystem team
developerOrganization: api.video
developerOrganizationUrl: https://api.video
developerEmail: ecosystem@api.video
licenseName: MIT License
licenseUrl: http://www.opensource.org/licenses/mit-license.php
library: okhttp-gson
dateLibrary: threetenbp
artifactId: android-api-client
hideGenerationTimestamp: true
serializableModel: "true"
java8: "true"
android: "true"
client: "true"
defaultChunkSize: 50 * 1024 * 1024
minChunkSize: 5 * 1024 * 1024
maxChunkSize: 128 * 1024 * 1024

files:
  Environment.mustache:
    folder: src/main/java/video/api/client/api/models
    destinationFilename: Environment.java
  page.mustache:
    folder: src/main/java/video/api/client/api/models
    destinationFilename: Page.java
  ApiVideoAuthInterceptor.mustache:
    folder: src/main/java/video/api/client/api/auth
    destinationFilename: ApiVideoAuthInterceptor.java
  EmptyArrayFixTypeAdapterFactory.mustache:
    folder: src/main/java/video/api/client/api
    destinationFilename: EmptyArrayFixTypeAdapterFactory.java
  UploadChunkRequestBody.mustache:
    folder: src/main/java/video/api/client/api/upload
    destinationFilename: UploadChunkRequestBody.java
  UploadProgressListener.mustache:
    folder: src/main/java/video/api/client/api/upload
    destinationFilename: UploadProgressListener.java
  UploadPartProgressListener.mustache:
    folder: src/main/java/video/api/client/api/upload
    destinationFilename: UploadPartProgressListener.java
  ApiVideoClient.mustache:
    folder: src/main/java/video/api/client
    destinationFilename: ApiVideoClient.java
  pagination.md.mustache:
    folder: docs
    destinationFilename: Pagination.md
  post-generate-android.sh:
    destinationFilename: post-generate.sh
  maven-push.gradle.mustache:
    destinationFilename: maven-push.gradle
