licenseName: MIT
generateInterfaces: true
httpUserAgent: api.video client (GO; v:0.0.2; )
structPrefix: true
packageName: apivideosdk
goImportAlias: apivideosdk
gitUserId: apivideo
gitRepoId: go-api-client
ignoredFiles:
  - configuration.mustache
  - response.mustache
files:
  post-generate.sh:
    destinationFilename: post-generate.sh