artifactVersion: 0.0.3
licenseName: MIT
generateInterfaces: true
structPrefix: true
packageName: apivideosdk
goImportAlias: apivideosdk
gitUserId: apivideo
gitRepoId: go-api-client
ignoredFiles:
  - configuration.mustache
  - response.mustache
files:
  post-generate.sh:
    destinationFilename: post-generate.sh