artifactVersion: 0.0.9
licenseName: MIT
generateInterfaces: true
structPrefix: true
packageName: apivideosdk
goImportAlias: apivideosdk
gitUserId: apivideo
gitRepoId: go-api-client
ignoredFiles:
  - configuration.mustache
  - response.mustache
defaultChunkSize: 50 * 1024 * 1024
minChunkSize: 5 * 1024 * 1024
maxChunkSize: 128 * 1024 * 1024

files:
  post-generate.sh:
    destinationFilename: post-generate.sh