changelog:
  - 1.2.0 (2022-01-07):
    - Add watermark endpoints
    - Add video clips
  - 1.1.0 (2021-12-06):
    - Add `name` attribute in player themes
  - 1.0.0 (2021-11-15):
    - Add support of `progressive uploads`

licenseName: MIT
srcBasePath: src
variableNamingConvention: camelCase
invokerPackage: ApiVideo\Client
developerEmail: ecosystem@api.video
gitRepoId: api.video-php-client
defaultChunkSize: 50 * 1024 * 1024
minChunkSize: 5 * 1024 * 1024
maxChunkSize: 128 * 1024 * 1024
