packageVersion: 0.0.12
licenseInfo: MIT
packageName: apivideo
projectName: api.video
appShortDescription: api.video Python API client
infoName: api.video ecosystem team
infoEmail: ecosystem@api.video
packageUrl: https://github.com/apivideo/python-api-client
ignoredFiles:
  - gitlab-ci.mustache
  - travis.mustache
  - git_push.sh.mustache
  - model_test.mustache
files:
  post-generate.sh:
    destinationFilename: post-generate.sh