changelog:
  - 1.2.0 (2022-01-07):
    - Add watermark endpoints
    - Add video clips
    - Fix tags[] query parameter format of GET /videos
  - 1.1.0 (2021-12-06):
    - Add `name` attribute in player themes
  - 1.0.0 (2021-11-15):
    - Add support of `progressive uploads`

licenseInfo: MIT
packageName: apivideo
projectName: api.video
appShortDescription: api.video Python API client
infoName: api.video ecosystem team
infoEmail: ecosystem@api.video
packageUrl: https://github.com/apivideo/api.video-python-client
gitRepoId: api.video-python-client
ignoredFiles:
  - gitlab-ci.mustache
  - travis.mustache
  - git_push.sh.mustache
  - model_test.mustache
defaultChunkSize: 50 * 1024 * 1024
minChunkSize: 5 * 1024 * 1024
maxChunkSize: 128 * 1024 * 1024
files:
  post-generate.sh:
    destinationFilename: post-generate.sh