changelog:
  - 1.0.2 (2022-03-11):
      - Add Origin identification headers
  - 1.0.1 (2022-01-24):
      - Add applicationName parameter (to allow user agent extension)
  - 1.0.0 (2022-01-07):
      - Add watermark endpoints
      - Add video clips
      - Fix tags[] query parameter format of GET /videos
      - Correctly distinguish between "undefined", "defined" and "null" values if the playerId parameter of PATCH /videos/{videoId}
  - 0.1.2 (2021-12-14):
      - Set protocol for progressive upload session visibility to public
  - 0.1.1 (2021-12-14):
        - Add a protocol for progressive upload session
  - 0.1.0 (2021-12-06):
      - Initial release

library: alamofire
generateAliasAsModel: true
removeMigrationProjectNameClass: true
swiftPackagePath: "Sources"
originClient: ios
client: "true"
gitRepoId: api.video-ios-client
additionalProperties:
  projectName: ApiVideoClient
  podAuthors: "{ 'Ecosystem Team' => 'ecosystem@api.video' }"
  podSummary: "The official iOS client library for api.video"
  podRepo: https://github.com/apivideo/api.video-ios-client
  podHomepage: https://docs.api.video
  podSocialMediaUrl: https://twitter.com/api_video
  podLicense: "{ :type => 'MIT' }"
defaultChunkSize: 50 * 1024 * 1024
minChunkSize: 5 * 1024 * 1024
maxChunkSize: 128 * 1024 * 1024

files:
  Auth/ApiVideoCredential.mustache:
    folder: Sources/Auth
    destinationFilename: ApiVideoCredential.swift
  Auth/ApiVideoAuthenticator.mustache:
    folder: Sources/Auth
    destinationFilename: ApiVideoAuthenticator.swift
  Environment.mustache:
    folder: Sources/Models
    destinationFilename: Environment.swift
  Upload/ProgressiveUploadSessioning.mustache:
    folder: Sources/Upload
    destinationFilename: ProgressiveUploadSessioning.swift
  Upload/ChunkInputStream.mustache:
    folder: Sources/Upload
    destinationFilename: ChunkInputStream.swift
  Upload/FileChunksBuilder.mustache:
    folder: Sources/Upload
    destinationFilename: FileChunksBuilder.swift
  Upload/FileReaders.mustache:
    folder: Sources/Upload
    destinationFilename: FileReaders.swift
  NullableString.mustache:
    folder: Sources/Models
    destinationFilename: NullableString.swift
  post-generate.sh:
    destinationFilename: post-generate.sh
