licenseName: MIT
supportsES6: true
npmName: "@api.video/typescript-api-client"
npmVersion: 1.0.0
npmDescription: api.video java API client
npmAuthor: api.video ecosystem team
ignoredFiles:
  - api/baseapi.mustache
  - api/auth.mustache
  - api/exception.mustache
  - api/middleware.mustache
  - auth/auth.mustache
  - configuration.mustache
  - git_push.sh.mustache
  - http/http.mustache
  - http/isomorphic-fetch.mustache
  - http/servers.mustache
  - middleware.mustache
  - model/models_all.mustache
  - rxjsStub.mustache
  - servers.mustache
  - services/configuration.mustache
  - types/ObjectParamAPI.mustache
  - types/ObservableAPI.mustache
  - types/PromiseAPI.mustache
  - util.mustache
responseExamplePayloadFolder: tests/payloads
files:
  gitignore:
    folder: .
    destinationFilename: .gitignore
  client/HttpClient.ts:
    folder: client/
    destinationFilename: HttpClient.ts
  client/ErrorHandler.ts:
    folder: client/
    destinationFilename: ErrorHandler.ts